// Resize handle styles
export const resizeHandleCss = () => {
	return {
		top: {
			width: 26,
			height: 6,
			background: '#fff',
			border: '2px solid #6180E4',
			borderRadius: '32px',
			top: '-4px',
			left: '50%',
			transform: 'translate(-50%, 0%)',
			zIndex: 99,
		},
		bottom: {
			width: 26,
			height: 6,
			background: '#fff',
			border: '2px solid #6180E4',
			borderRadius: '32px',
			top: 'calc(100% - 2px)',
			left: '50%',
			transform: 'translate(-50%, 0px)',
			zIndex: 99,
		},
		left: {
			width: 26,
			height: 6,
			background: '#fff',
			border: '2px solid #6180E4',
			borderRadius: '32px',
			top: '50%',
			left: '-14px',
			transform: 'translate(0px, -50%) rotate(90deg)',
			zIndex: 99,
		},
		right: {
			width: 26,
			height: 6,
			background: '#fff',
			border: '2px solid #6180E4',
			borderRadius: '32px',
			top: '50%',
			left: 'calc(100% + 1px)',
			transform: 'translate(-50%, 0px) rotate(90deg)',
			zIndex: 99,
		},
		bottomRight: {
			width: 16,
			height: 16,
			right: '-10px',
			bottom: '-10px',
			zIndex: 99,
			border: '3px solid #FFFFFF',
			background: '#3E64DE',
			borderRadius: '50%',
		},
		bottomLeft: {
			width: 16,
			height: 16,
			left: '-10px',
			bottom: '-10px',
			zIndex: 99,
			border: '3px solid #FFFFFF',
			background: '#3E64DE',
			borderRadius: '50%',
		},
		topLeft: {
			width: 16,
			height: 16,
			left: '-10px',
			top: '-10px',
			zIndex: 99,
			border: '3px solid #FFFFFF',
			background: '#3E64DE',
			borderRadius: '50%',
		},
		topRight: {
			width: 16,
			height: 16,
			right: '-10px',
			top: '-10px',
			zIndex: 99,
			border: '3px solid #FFFFFF',
			background: '#3E64DE',
			borderRadius: '50%',
		},
	};
};
