// Mock data for email templates
const mockEmailTemplates = [
	{
		id: '1',
		name: 'Welcome Email',
		subject: 'Welcome to our platform!',
		description: 'A warm welcome email for new users',
		thumbnail: '/api/placeholder/300/200',
		createdAt: '2024-01-15',
		updatedAt: '2024-01-20',
		author: 'John Doe',
		status: 'published',
		category: 'onboarding',
		opens: 1250,
		clicks: 89,
	},
	{
		id: '2',
		name: 'Newsletter Template',
		subject: 'Monthly Newsletter - January 2024',
		description: 'Monthly newsletter template with latest updates',
		thumbnail: '/api/placeholder/300/200',
		createdAt: '2024-01-10',
		updatedAt: '2024-01-18',
		author: 'Jane Smith',
		status: 'draft',
		category: 'newsletter',
		opens: 890,
		clicks: 45,
	},
	{
		id: '3',
		name: 'Product Launch',
		subject: 'Introducing our new product!',
		description: 'Announcement email for new product launch',
		thumbnail: '/api/placeholder/300/200',
		createdAt: '2024-01-08',
		updatedAt: '2024-01-16',
		author: 'Mike Johnson',
		status: 'published',
		category: 'marketing',
		opens: 2100,
		clicks: 156,
	},
	{
		id: '4',
		name: 'Password Reset',
		subject: 'Reset your password',
		description: 'Security email for password reset requests',
		thumbnail: '/api/placeholder/300/200',
		createdAt: '2024-01-05',
		updatedAt: '2024-01-14',
		author: 'Sarah Wilson',
		status: 'published',
		category: 'transactional',
		opens: 450,
		clicks: 23,
	},
	{
		id: '5',
		name: 'Order Confirmation',
		subject: 'Your order has been confirmed',
		description: 'Confirmation email for successful orders',
		thumbnail: '/api/placeholder/300/200',
		createdAt: '2024-01-03',
		updatedAt: '2024-01-12',
		author: 'Tom Brown',
		status: 'published',
		category: 'transactional',
		opens: 1800,
		clicks: 234,
	},
	{
		id: '6',
		name: 'Holiday Sale',
		subject: 'Special Holiday Offers - 50% Off!',
		description: 'Promotional email for holiday season sales',
		thumbnail: '/api/placeholder/300/200',
		createdAt: '2024-01-01',
		updatedAt: '2024-01-10',
		author: 'Lisa Davis',
		status: 'scheduled',
		category: 'promotional',
		opens: 3200,
		clicks: 412,
	},
];

export default mockEmailTemplates;
